CREATE TABLE BREWERY (
  BREWERY_ID SMALLINT NOT NULL,
  NAME VARCHAR(175)
);

CREATE TABLE BEER (
  BEER_ID SMALLINT NOT NULL,
  BEER_NAME VARCHAR(60) NOT NULL,
  STYLE VARCHAR(25) NOT NULL,
  VOLUME SMALLINT NOT NULL,
  QUANTITY SMALLINT NOT NULL,
  BOTTLE_DATE DATE NOT NULL,
  LOCATION VARCHAR(25) NOT NULL,
  BREWERY_ID SMALLINT NOT NULL
);

ALTER TABLE BREWERY ADD PRIMARY KEY (BREWERY_ID);
ALTER TABLE BEER ADD PRIMARY KEY (BEER_ID);
ALTER TABLE BEER ADD FOREIGN KEY (BREWERY_ID) REFERENCES BREWERY(BREWERY_ID);

-- INSERT INTO BREWERY
INSERT INTO BREWERY VALUES (1, 'TEST');
INSERT INTO BREWERY VALUES (2, 'TEST2');

-- INSERT INTO BEER
INSERT INTO BEER VALUES (1, 'TESTNAME', 'IPA', 12, 1, '2016-08-04', 'TEST_LOC', 1);