DROP TABLE BREWERY IF EXISTS;
DROP TABLE BEER IF EXISTS;

CREATE TABLE BREWERY (
  BREWERY_ID SMALLINT NOT NULL,
  NAME VARCHAR(175) NOT NULL
);

CREATE TABLE BEER (
  BEER_ID SMALLINT NOT NULL,
  NAME VARCHAR(60) NOT NULL,
  STYLE VARCHAR(25) NOT NULL,
  VOLUME SMALLINT NOT NULL,
  QUANTITY SMALLINT NOT NULL,
  BOTTLE_DATE DATE NOT NULL,
  LOCATION VARCHAR(25) NOT NULL,
  BREWERY_ID SMALLINT NOT NULL
);

ALTER TABLE BREWERY ADD PRIMARY KEY (BREWERY_ID);
ALTER TABLE BEER ADD PRIMARY KEY (BEER_ID);
ALTER TABLE BEER ADD FOREIGN KEY (BREWERY_ID) REFERENCES BREWERY(BREWERY_ID);