-- INSERT INTO BREWERY
INSERT INTO BREWERY VALUES (1, 'TEST');
INSERT INTO BREWERY VALUES (2, 'TEST2');

-- INSERT INTO BEER
INSERT INTO BEER VALUES(1, 'TESTNAME', 'IPA', 12, 1, '2016-08-04', 'TEST_LOC', 1);